listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/

connection projet-elfe
address mqtt.projet-elfe.fr
topic tele/# both 0
topic hasp/# both 0
topic cmnd/# both 0
